name: CI

on:
  push:
    branches: [ master, develop, py3, ci ]
  pull_request:
    branches: [ master, develop, py3, ci ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false

      - name: Cache Testing Data
        id: cache-test-data
        uses: actions/cache@v2
        with:
          path: testdata
          key: testdata

      - name: Download Testing Data
        if: steps.cache-test-data.outputs.cache-hit != 'true'
        run: |
          pip3 install wheel
          pip3 install setuptools
          pip3 install zenodo-get
          python3 -m zenodo_get 10.5281/zenodo.3950299 --output-dir=testdata

      - name: Set Testing Data Envvar
        run: |
          echo "TEST_DIRECTORY=$(realpath testdata)" >> $GITHUB_ENV

      - name: Install SAMtools
        run: |
          wget https://sourceforge.net/projects/samtools/files/samtools/1.7/samtools-1.7.tar.bz2/download -O samtools-1.7.tar.bz2
          tar xvjf samtools-1.7.tar.bz2
          (cd samtools-1.7 && ./configure && make)
          echo $(realpath samtools-1.7) >> $GITHUB_PATH

      - name: Install BCFTools
        run: |
          wget https://sourceforge.net/projects/samtools/files/samtools/1.7/bcftools-1.7.tar.bz2/download -O bcftools-1.7.tar.bz2
          tar xvjf bcftools-1.7.tar.bz2
          (cd bcftools-1.7 && ./configure && make)
          echo $(realpath bcftools-1.7) >> $GITHUB_PATH

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox and any other packages
        run: |
          python -m pip install coverage tox tox-gh-actions

      - name: Test with tox
        run: |
          tox
        env:
          PLATFORM: ${{ matrix.python }}
